<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/01_pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
data={"name":["Jeel","Heet","Daksh"],
      "age":[20,10,19],
      "Marks":[20,8,11]}

In [5]:
df=pd.DataFrame(data)
print(df)

    name  age  Marks
0   Jeel   20     20
1   Heet   10      8
2  Daksh   19     11

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [9]:
print(df.shape)

(3, 3)

In [14]:
print(df.columns)

Index(['name', 'age', 'Marks'], dtype='object')

In [16]:
print(df.head(2))

   name  age  Marks
0  Jeel   20     20
1  Heet   10      8

In [17]:
print(df.tail(1))

    name  age  Marks
2  Daksh   19     11

In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

In [23]:
df.describe()

             age      Marks
count   3.000000   3.000000
mean   16.333333  13.000000
std     5.507571   6.244998
min    10.000000   8.000000
25%    14.500000   9.500000
50%    19.000000  11.000000
75%    19.500000  15.500000
max    20.000000  20.000000

In [24]:
df.describe(include="all")

        name        age      Marks
count      3   3.000000   3.000000
unique     3        NaN        NaN
top     Jeel        NaN        NaN
freq       1        NaN        NaN
mean     NaN  16.333333  13.000000
std      NaN   5.507571   6.244998
min      NaN  10.000000   8.000000
25%      NaN  14.500000   9.500000
50%      NaN  19.000000  11.000000
75%      NaN  19.500000  15.500000
max      NaN  20.000000  20.000000

In [20]:
print(df.dtypes)

name     object
age       int64
Marks     int64
dtype: object

In [25]:
df.size

9

In [27]:
df.values

array([['Jeel', 20, 20],
       ['Heet', 10, 8],
       ['Daksh', 19, 11]], dtype=object)