<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/03_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
data = {
    "Name": ["Jeel", "Rahul", "Amit", "Priya"],
    "Age": [20, 21, 19, 20],
    "Marks": [85, 92, 76, 88],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai"]
}
df= pd.DataFrame(data)
print(df.head)

<bound method NDFrame.head of     Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai>

In [16]:
print(df["Name"])
print(df[["Name","Marks"]])

0     Jeel
1    Rahul
2     Amit
3    Priya
Name: Name, dtype: object
    Name  Marks
0   Jeel     85
1  Rahul     92
2   Amit     76
3  Priya     88

In [17]:
df.shape

(4, 4)

In [18]:
df.size

16

In [19]:
df.dtypes

Name     object
Age       int64
Marks     int64
City     object
dtype: object

In [21]:
df["passed"]= df["Marks"] >=80
print(df)

    Name  Age  Marks    City  passed
0   Jeel   20     85  Mumbai    True
1  Rahul   21     92    Pune    True
2   Amit   19     76   Surat   False
3  Priya   20     88  Mumbai    True

In [23]:
df["Bonus Marks"]= df["Marks"] +5
print(df)

    Name  Age  Marks    City  passed  Bonus Marks
0   Jeel   20     85  Mumbai    True           90
1  Rahul   21     92    Pune    True           97
2   Amit   19     76   Surat   False           81
3  Priya   20     88  Mumbai    True           93

In [24]:
df.drop("Bonus Marks",axis=1)

    Name  Age  Marks    City  passed
0   Jeel   20     85  Mumbai    True
1  Rahul   21     92    Pune    True
2   Amit   19     76   Surat   False
3  Priya   20     88  Mumbai    True

In [25]:
print(df.iloc[2])

Name            Amit
Age               19
Marks             76
City           Surat
passed         False
Bonus Marks       81
Name: 2, dtype: object

In [27]:
df.head()

    Name  Age  Marks    City  passed  Bonus Marks
0   Jeel   20     85  Mumbai    True           90
1  Rahul   21     92    Pune    True           97
2   Amit   19     76   Surat   False           81
3  Priya   20     88  Mumbai    True           93

In [28]:
df.tail()

    Name  Age  Marks    City  passed  Bonus Marks
0   Jeel   20     85  Mumbai    True           90
1  Rahul   21     92    Pune    True           97
2   Amit   19     76   Surat   False           81
3  Priya   20     88  Mumbai    True           93

In [33]:
df.describe(include="all")

        Name        Age      Marks    City passed  Bonus Marks
count      4   4.000000   4.000000       4      4     4.000000
unique     4        NaN        NaN       3      2          NaN
top     Jeel        NaN        NaN  Mumbai   True          NaN
freq       1        NaN        NaN       2      3          NaN
mean     NaN  20.000000  85.250000     NaN    NaN    90.250000
std      NaN   0.816497   6.800735     NaN    NaN     6.800735
min      NaN  19.000000  76.000000     NaN    NaN    81.000000
25%      NaN  19.750000  82.750000     NaN    NaN    87.750000
50%      NaN  20.000000  86.500000     NaN    NaN    91.500000
75%      NaN  20.250000  89.000000     NaN    NaN    94.000000
max      NaN  21.000000  92.000000     NaN    NaN    97.000000

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      object
 1   Age          4 non-null      int64
 2   Marks        4 non-null      int64
 3   City         4 non-null      object
 4   passed       4 non-null      bool
 5   Bonus Marks  4 non-null      int64
dtypes: bool(1), int64(3), object(2)
memory usage: 296.0+ bytes