<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/04_indexing_and_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 92, 76, 88, 95],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi"]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [3]:
print(df.loc[0])

Name       Jeel
Age          20
Marks        85
City     Mumbai
Name: 0, dtype: object

In [5]:
print(df.iloc[0])

Name       Jeel
Age          20
Marks        85
City     Mumbai
Name: 0, dtype: object

In [6]:
df.loc[0,"Marks"]

np.int64(85)

In [7]:
df.iloc[0,2]

np.int64(85)

In [8]:
df.loc[:, ["Name", "Marks"]]

    Name  Marks
0   Jeel     85
1  Rahul     92
2   Amit     76
3  Priya     88
4   Neha     95

In [9]:
df.loc[[0,2,4]]

   Name  Age  Marks    City
0  Jeel   20     85  Mumbai
2  Amit   19     76   Surat
4  Neha   22     95   Delhi

In [13]:
df.iloc[[0,2,4],[0,3]]

   Name    City
0  Jeel  Mumbai
2  Amit   Surat
4  Neha   Delhi

In [14]:
df.iloc[1:4]

    Name  Age  Marks    City
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai

In [15]:
df.loc[1:4]

    Name  Age  Marks    City
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [16]:
df.iloc[:, 0:3]

    Name  Age  Marks
0   Jeel   20     85
1  Rahul   21     92
2   Amit   19     76
3  Priya   20     88
4   Neha   22     95

In [20]:
df.index = ["A", "B", "C", "D", "E"]

In [23]:
df.loc["B", "Marks"]

np.int64(92)

In [24]:
df.loc["C"]

Name      Amit
Age         19
Marks       76
City     Surat
Name: C, dtype: object

In [25]:
df.iloc[2]

Name      Amit
Age         19
Marks       76
City     Surat
Name: C, dtype: object

**Cheat Sheet**<br>
.loc<br>
│<br>
├── label based<br>
├── df.loc["A"]<br>
├── df.loc["A", "Marks"]<br>
├── df.loc[:, "Marks"]<br>
├── df.loc[:, ["Name", "Marks"]]<br>
└── df.loc["A":"C"]<br>
<br><br>
.iloc<br>
│<br>
├── position based<br>
├── df.iloc[0]<br>
├── df.iloc[0, 2]<br>
├── df.iloc[:, 2]<br>
├── df.iloc[:, [0, 2]]<br>
└── df.iloc[0:3]<br>