<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/05_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



**Most Imp** : df[condition]

In [20]:
import pandas as pd

In [21]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 92, 76, 88, 95],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi"]
})
print(df)

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [22]:
df["Marks"] > 80

0     True
1     True
2    False
3     True
4     True
Name: Marks, dtype: bool

In [23]:
df[df["Marks"] > 80]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [24]:
df[df["City"] == "Mumbai"]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
3  Priya   20     88  Mumbai

In [25]:
df[(df["City"] == "Mumbai") | (df["City"] == "Pune")]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
3  Priya   20     88  Mumbai

In [26]:
df[(df["City"] == "Mumbai") | (df["City"] == "Pune")]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
3  Priya   20     88  Mumbai

In [27]:
df[df["City"].isin(["Mumbai", "Pune", "Delhi"])]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [28]:
df[df["Marks"].between(80, 90)]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
3  Priya   20     88  Mumbai

In [29]:
df[df["Name"].str.startswith("J")]
df[df["Name"].str.endswith("a")]

    Name  Age  Marks    City
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [30]:
df.loc[
    df["Marks"] > 80,
    ["Name", "Marks"]
]

    Name  Marks
0   Jeel     85
1  Rahul     92
3  Priya     88
4   Neha     95

In [31]:
df[df["Marks"].notna()]

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [32]:
df[df["Marks"].isna()]

Empty DataFrame
Columns: [Name, Age, Marks, City]
Index: []