<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/06_modifying_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 92, 76, 88, 95],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi"]
})

In [ ]:
df.loc[0,"Marks"]=90

In [ ]:
df.iloc[0, 2] = 90

In [ ]:
df["Marks"] = df["Marks"] + 5

In [ ]:
df["Passed"] = df["Marks"] >= 40

In [ ]:
df

    Name  Age  Marks    City  Passed
0   Jeel   20     95  Mumbai    True
1  Rahul   21     97    Pune    True
2   Amit   19     81   Surat    True
3  Priya   20     93  Mumbai    True
4   Neha   22    100   Delhi    True

In [ ]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 92, 76, 88, 95],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi"]
})
df

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

**df.loc[condition, "column"] = new_value**

In [ ]:
df.loc[df["Marks"] < 80, "Marks"] += 5

In [ ]:
df

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     81   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [ ]:
df["City"] = df["City"].replace("Mumbai", "Bombay")

In [ ]:
df["City"] = df["City"].replace({
    "Mumbai": "Bombay",
    "Pune": "Poona"
})
df

    Name  Age  Marks    City
0   Jeel   20     85  Bombay
1  Rahul   21     92   Poona
2   Amit   19     81   Surat
3  Priya   20     88  Bombay
4   Neha   22     95   Delhi

In [ ]:
df = df.rename(columns={
    "Name": "Student_Name",
    "Age": "Student_Age"
})
df

  Student_Name  Student_Age  Marks    City
0         Jeel           20     85  Bombay
1        Rahul           21     92   Poona
2         Amit           19     81   Surat
3        Priya           20     88  Bombay
4         Neha           22     95   Delhi

In [ ]:
df = df.rename(index={
    0: "A",
    1: "B",
    2: "C",
    3: "D",
    4: "E"
})

In [ ]:
df

  Student_Name  Student_Age  Marks    City
A         Jeel           20     85  Bombay
B        Rahul           21     92   Poona
C         Amit           19     81   Surat
D        Priya           20     88  Bombay
E         Neha           22     95   Delhi

In [ ]:
df.loc["F"] = ["Karan", 21, 82, "Ahmedabad"]

In [ ]:
df

  Student_Name  Student_Age  Marks       City
A         Jeel           20     85     Bombay
B        Rahul           21     92      Poona
C         Amit           19     81      Surat
D        Priya           20     88     Bombay
E         Neha           22     95      Delhi
F        Karan           21     82  Ahmedabad

In [ ]:
df = df.drop("F")

In [ ]:
#df = df.drop(2)

In [ ]:
df = df.drop("Student_Age", axis=1)

In [ ]:
#df["Country"] = "India"

In [ ]:
df

  Student_Name  Marks    City
A         Jeel     85  Bombay
B        Rahul     92   Poona
C         Amit     81   Surat
D        Priya     88  Bombay
E         Neha     95   Delhi

In [ ]:
df.insert(1, "Country", "USA")

In [ ]:
df

  Student_Name Country  Marks    City
A         Jeel     USA     85  Bombay
B        Rahul     USA     92   Poona
C         Amit     USA     81   Surat
D        Priya     USA     88  Bombay
E         Neha     USA     95   Delhi

In [ ]:
df["City"] = df["City"].replace("Delhi", "New Delhi")

In [ ]:
df

  Student_Name Country  Marks    City
A         Jeel     USA     85  Bombay
B        Rahul     USA     92   Poona
C         Amit     USA     81   Surat
D        Priya     USA     88  Bombay
E         Neha     USA     95   Delhi

In [ ]:
df.loc[(df["City"] == "Mumbai") & (df["Marks"] > 80),"Marks"] += 5
df

  Student_Name Country  Marks       City
A         Jeel     USA     85     Bombay
B        Rahul     USA     92      Poona
C         Amit     USA     81      Surat
D        Priya     USA     88     Bombay
E         Neha     USA     95  New Delhi

In [ ]:
print(df.loc[df["City"] == "Bombay"])

  Student_Name Country  Marks    City
A         Jeel     USA     85  Bombay
D        Priya     USA     88  Bombay

| Task                             | Code                                                              |
| -------------------------------- | ----------------------------------------------------------------- |
| Change single value              | `df.loc[0, "Marks"] = 90`                                         |
| Change by position               | `df.iloc[0, 2] = 90`                                              |
| Modify entire column             | `df["Marks"] = df["Marks"] + 5`                                   |
| Add new column                   | `df["Passed"] = df["Marks"] >= 40`                                |
| Conditional update               | `df.loc[df["Marks"] < 40, "Marks"] = 40`                          |
| Conditional update + calculation | `df.loc[df["Marks"] < 80, "Marks"] += 5`                          |
| Replace value                    | `df["City"] = df["City"].replace("Mumbai", "Bombay")`             |
| Multiple replacements            | `df["City"].replace({"Mumbai":"Bombay", "Pune":"Poona"})`         |
| Rename column                    | `df.rename(columns={"Marks":"Score"})`                            |
| Rename multiple columns          | `df.rename(columns={"Name":"Student_Name", "Age":"Student_Age"})` |
| Rename index                     | `df.rename(index={0:"A", 1:"B"})`                                 |
| Add row                          | `df.loc["F"] = ["Karan", 21, 82, "Ahmedabad"]`                    |
| Delete row                       | `df.drop("F")`                                                    |
| Delete column                    | `df.drop(columns="Age")`                                          |
| Add column at position           | `df.insert(1, "Country", "India")`                                |