<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/07_missing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, np.nan, 20, 22],
    "Marks": [85, np.nan, 76, 88, np.nan],
    "City": ["Mumbai", "Pune", "Surat", np.nan, "Delhi"]
})

df

    Name   Age  Marks    City
0   Jeel  20.0   85.0  Mumbai
1  Rahul  21.0    NaN    Pune
2   Amit   NaN   76.0   Surat
3  Priya  20.0   88.0     NaN
4   Neha  22.0    NaN   Delhi

In [27]:
df.isna()

    Name    Age  Marks   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False   True
4  False  False   True  False

In [28]:
df.isna().sum()

Name     0
Age      1
Marks    2
City     1
dtype: int64

In [29]:
df[df.isna().any(axis=1)]

    Name   Age  Marks   City
1  Rahul  21.0    NaN   Pune
2   Amit   NaN   76.0  Surat
3  Priya  20.0   88.0    NaN
4   Neha  22.0    NaN  Delhi

In [30]:
df[df.notna().all(axis=1)]

   Name   Age  Marks    City
0  Jeel  20.0   85.0  Mumbai

In [35]:
df.dropna(subset=["Marks"])

    Name   Age  Marks    City
0   Jeel  20.0   85.0  Mumbai
2   Amit   NaN   76.0   Surat
3  Priya  20.0   88.0     NaN

In [36]:
df.dropna(axis=1)

    Name
0   Jeel
1  Rahul
2   Amit
3  Priya
4   Neha

In [37]:
df["Marks"] = df["Marks"].fillna(0)

In [38]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [39]:
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

In [40]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [41]:
df.isna().sum()

Name     0
Age      0
Marks    0
City     0
dtype: int64