<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/08_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 92, 76, 88, 95],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi"]
})

df

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi

In [11]:
df.sort_values("Marks")

    Name  Age  Marks    City
2   Amit   19     76   Surat
0   Jeel   20     85  Mumbai
3  Priya   20     88  Mumbai
1  Rahul   21     92    Pune
4   Neha   22     95   Delhi

In [12]:
df.sort_values("Marks", ascending=False)

    Name  Age  Marks    City
4   Neha   22     95   Delhi
1  Rahul   21     92    Pune
3  Priya   20     88  Mumbai
0   Jeel   20     85  Mumbai
2   Amit   19     76   Surat

In [13]:
df.sort_values("Name")

    Name  Age  Marks    City
2   Amit   19     76   Surat
0   Jeel   20     85  Mumbai
4   Neha   22     95   Delhi
3  Priya   20     88  Mumbai
1  Rahul   21     92    Pune

In [14]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 92, 76, 88, 95]
})

In [15]:
df.sort_values(["Age", "Marks"])

    Name  Age  Marks
2   Amit   19     76
0   Jeel   20     85
3  Priya   20     88
1  Rahul   21     92
4   Neha   22     95

In [16]:
df.sort_values(
    ["Age", "Marks"],
    ascending=[True, False]
)

    Name  Age  Marks
2   Amit   19     76
3  Priya   20     88
0   Jeel   20     85
1  Rahul   21     92
4   Neha   22     95

In [17]:
df = pd.DataFrame(
    {"Marks": [85, 92, 76]},
    index=["C", "A", "B"]
)

df

   Marks
C     85
A     92
B     76

In [18]:
df.sort_index()

   Marks
A     92
B     76
C     85

In [19]:
df.nlargest(3, "Marks")

   Marks
A     92
C     85
B     76

In [20]:
df.nsmallest(1, "Marks")

   Marks
B     76

| Task             | Code                                                      |
| ---------------- | --------------------------------------------------------- |
| Sort column      | `df.sort_values("Marks")`                                 |
| Descending       | `df.sort_values("Marks", ascending=False)`                |
| Multiple columns | `df.sort_values(["Age", "Marks"])`                        |
| Different orders | `df.sort_values(["Age","Marks"], ascending=[True,False])` |
| Sort index       | `df.sort_index()`                                         |
| Top 3            | `df.nlargest(3, "Marks")`                                 |
| Bottom 3         | `df.nsmallest(3, "Marks")`                                |