<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/10_groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha", "Karan"],
    "Age": [20, 21, 19, 20, 22, 21],
    "Marks": [85, 92, 76, 88, 95, 82],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi", "Pune"]
})

df

    Name  Age  Marks    City
0   Jeel   20     85  Mumbai
1  Rahul   21     92    Pune
2   Amit   19     76   Surat
3  Priya   20     88  Mumbai
4   Neha   22     95   Delhi
5  Karan   21     82    Pune

In [4]:
df.groupby("City")

In [5]:
df.groupby("City")["Marks"].mean()

City
Delhi     95.0
Mumbai    86.5
Pune      87.0
Surat     76.0
Name: Marks, dtype: float64

In [6]:
df.groupby("City")["Marks"].sum()

City
Delhi      95
Mumbai    173
Pune      174
Surat      76
Name: Marks, dtype: int64

In [7]:
df.groupby("City")["Name"].count()

City
Delhi     1
Mumbai    2
Pune      2
Surat     1
Name: Name, dtype: int64

In [8]:
df["City"].value_counts()

City
Mumbai    2
Pune      2
Surat     1
Delhi     1
Name: count, dtype: int64

In [13]:
df.groupby("City")["Name"].count()

City
Delhi     1
Mumbai    2
Pune      2
Surat     1
Name: Name, dtype: int64

In [14]:
df.groupby(["City", "Age"])["Marks"].mean()

City    Age
Delhi   22     95.0
Mumbai  20     86.5
Pune    21     87.0
Surat   19     76.0
Name: Marks, dtype: float64

In [15]:
df.groupby("City")["Marks"].mean().sort_values(ascending=False)

City
Delhi     95.0
Pune      87.0
Mumbai    86.5
Surat     76.0
Name: Marks, dtype: float64

In [16]:
result = df.groupby("City")["Marks"].mean().reset_index()

| Task                             | Code                                                              |
| -------------------------------- | ----------------------------------------------------------------- |
| Group by column                  | `df.groupby("City")`                                              |
| Average                          | `df.groupby("City")["Marks"].mean()`                              |
| Sum                              | `df.groupby("City")["Marks"].sum()`                               |
| Minimum                          | `df.groupby("City")["Marks"].min()`                               |
| Maximum                          | `df.groupby("City")["Marks"].max()`                               |
| Count                            | `df.groupby("City")["Name"].count()`                              |
| Multiple statistics              | `df.groupby("City")["Marks"].agg(["mean","min","max"])`           |
| Multiple grouping columns        | `df.groupby(["City","Age"])["Marks"].mean()`                      |
| Multiple columns                 | `df.groupby("City")[["Marks","Age"]].mean()`                      |
| Sort grouped result              | `df.groupby("City")["Marks"].mean().sort_values(ascending=False)` |
| Convert result back to DataFrame | `.reset_index()`                                                  |