<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/11_combining_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd

In [25]:
df1 = pd.DataFrame({
    "Name": ["Jeel", "Rahul"],
    "Marks": [85, 92]
})

df2 = pd.DataFrame({
    "NAme": ["Amit", "Priya"],
    "Marks": [76, 88]
})

df1

    Name  Marks
0   Jeel     85
1  Rahul     92

In [26]:
df2

    NAme  Marks
0   Amit     76
1  Priya     88

In [27]:
result = pd.concat([df1, df2])
result

    Name  Marks   NAme
0   Jeel     85    NaN
1  Rahul     92    NaN
0    NaN     76   Amit
1    NaN     88  Priya

In [28]:
result = pd.concat([df1, df2], ignore_index=True)

result

    Name  Marks   NAme
0   Jeel     85    NaN
1  Rahul     92    NaN
2    NaN     76   Amit
3    NaN     88  Priya

In [29]:
df1 = pd.DataFrame({
    "Name": ["Jeel", "Rahul"],
    "Marks": [85, 92]
})

df2 = pd.DataFrame({
    "City": ["Mumbai", "Pune"],
    "Age": [20, 21]
})

pd.concat([df1, df2], axis=1)

    Name  Marks    City  Age
0   Jeel     85  Mumbai   20
1  Rahul     92    Pune   21

In [30]:
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Jeel", "Rahul", "Amit"]
})
marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 92, 76]
})

In [31]:
pd.merge(students,marks,on="ID")

   ID   Name  Marks
0   1   Jeel     85
1   2  Rahul     92
2   3   Amit     76

In [32]:
pd.merge(students, marks, on="ID", how="inner")

   ID   Name  Marks
0   1   Jeel     85
1   2  Rahul     92
2   3   Amit     76

In [34]:
pd.merge(students, marks, on="ID", how="outer")

   ID   Name  Marks
0   1   Jeel     85
1   2  Rahul     92
2   3   Amit     76

In [35]:
pd.merge(students, marks, on="ID", how="left")

   ID   Name  Marks
0   1   Jeel     85
1   2  Rahul     92
2   3   Amit     76

In [36]:
pd.merge(students, marks, on="ID", how="right")

   ID   Name  Marks
0   1   Jeel     85
1   2  Rahul     92
2   3   Amit     76

In [37]:
df1 = pd.DataFrame({
    "Name": ["Jeel", "Rahul"],
    "Marks": [85, 92]
}, index=[1, 2])

df2 = pd.DataFrame({
    "City": ["Mumbai", "Pune"]
}, index=[1, 2])

In [38]:
df1.join(df2)
df1

    Name  Marks
1   Jeel     85
2  Rahul     92

# Rows
pd.concat([df1, df2])

# Rows + fresh index
pd.concat([df1, df2], ignore_index=True)

# Columns
pd.concat([df1, df2], axis=1)

# Merge using common column
pd.merge(df1, df2, on="ID")

# Inner
pd.merge(df1, df2, on="ID", how="inner")

# Left
pd.merge(df1, df2, on="ID", how="left")

# Right
pd.merge(df1, df2, on="ID", how="right")

# Outer
pd.merge(df1, df2, on="ID", how="outer")

# Join using index
df1.join(df2)