<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/13_datetime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya"],
    "Joining_Date": [
        "2025-06-15",
        "2025-07-20",
        "2026-01-10",
        "2026-03-25"
    ]
})

df

    Name Joining_Date
0   Jeel   2025-06-15
1  Rahul   2025-07-20
2   Amit   2026-01-10
3  Priya   2026-03-25

In [4]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

In [6]:
df["Joining_Date"].dt.year

0    2025
1    2025
2    2026
3    2026
Name: Joining_Date, dtype: int32

In [7]:
df["Joining_Date"].dt.month

0    6
1    7
2    1
3    3
Name: Joining_Date, dtype: int32

In [9]:
df["Joining_Date"].dt.day

0    15
1    20
2    10
3    25
Name: Joining_Date, dtype: int32

In [10]:
df["Joining_Date"].dt.day_name()

0       Sunday
1       Sunday
2     Saturday
3    Wednesday
Name: Joining_Date, dtype: object

In [11]:
df["Year"] = df["Joining_Date"].dt.year
df["Month"] = df["Joining_Date"].dt.month
df["Day"] = df["Joining_Date"].dt.day

In [12]:
df[df["Joining_Date"] > "2026-01-01"]

    Name Joining_Date  Year  Month  Day
2   Amit   2026-01-10  2026      1   10
3  Priya   2026-03-25  2026      3   25

In [13]:
df.sort_values("Joining_Date", ascending=False)

    Name Joining_Date  Year  Month  Day
3  Priya   2026-03-25  2026      3   25
2   Amit   2026-01-10  2026      1   10
1  Rahul   2025-07-20  2025      7   20
0   Jeel   2025-06-15  2025      6   15

In [14]:
pd.Timestamp.today()

Timestamp('2026-09-05 08:36:35.868949')

In [15]:
pd.Timestamp.today().date()

datetime.date(2026, 9, 5)

In [16]:
date = pd.Timestamp("2026-09-05")

print(date)

2026-09-05 00:00:00

In [17]:
date = pd.Timestamp("2026-09-05")

date.strftime("%d-%m-%Y")

'05-09-2026'

In [18]:
pd.date_range(
    start="2026-09-01",
    end="2026-09-05"
)

DatetimeIndex(['2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04',
               '2026-09-05'],
              dtype='datetime64[ns]', freq='D')

pd.to_datetime(df["Date"])

df["Date"].dt.year
df["Date"].dt.month
df["Date"].dt.day
df["Date"].dt.day_name()

df.sort_values("Date")

pd.Timestamp.today()

pd.Timestamp("2026-09-05")

date.strftime("%d-%m-%Y")

pd.date_range("2026-09-01", periods=5)